baseURL = "https://nomnom.lislis.xyz"
DefaultContentLanguage = "de" 
languageCode = "de-de"
title = "(っ˘ڡ˘ς) NomNom"
theme = "hugo-theme-diary"
copyright = "Inhalte unter CC BY-SA"

[params]

enableOpenGraph = true
enableTwitterCards = true

[taxonomies]
   tag = "tags"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archiv"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

